### PR TITLE
[WIP] English usage

### PR DESCRIPTION
**Pull request by MercierCorentin**
I open this PR to discuss about English usage here. 
- Naming: English
- Comment: French
- PR and commit : English?
- Issues? 

What about doing everything in English?

### CODE REVIEW

**Comment by r0one** [comment]
English enables us to hire exchange students and devs outside UTC. It is very useful just for asking questions on forums: "hey, check my code, it's documented... in French" well no one will read it.

So I think we *should* do everything in English. Actually, even our variables are already in English, so there is no point in mixing English and French (devs must already speak English in order to understand the code).

But I said *should*, not *must*. English is just a general recommendation, but we're all volunteers and we badly need devs. So we cannot stop someone from coding just because he doesn't speak English. The most important thing is to code, and if someone does some things in French... Well, it's not too bad, eventually someone will check his code and fix that. But other languages such as Spanish or Chinese are **definitely not acceptable** because only a few people inside SiMDE will understand it and we won't be able to fix that.

UTC is international, but we're very small. If we were a bigger organisation, we may split the devs in several teams by language, and eventually merge the code in English. But as we're a small, unique team, everyone has to speak the same language, so that's either French or English. And if we don't have the time to translate everything and everyone speaks English, well every production (code, doc, PRs, etc.) should be in English. But everything external to our production (paradoxically, internal to SiMDE) can be in any language (i.e. we can continue to speak French on Slack if everyone does, but if we have international students in our team we should switch to English).

And actually, we could see that as challenge and a means to improve our skills at English! Why not speak English everywhere even on slack? (Yeah, I know, I'm a bit radical, but we've already tried to hire international students - and failed - so I'm not that crazy, language really was a barrier to their integration in our team).

**Comment by r0one** [comment]
Once we'll have settled about English **comments**, I'll approve the PR - no matter what we decide about comments.

**Review by r0one — CHANGES_REQUESTED** [review]
Should we do even **comments** in English?

**Comment by NastuzziSamy** [comment]
Actually, I think we should put everything in English. It is more accurate, and simpler for everyone. No confusions and it will allow us to pass LA13 successfully \o/

**Review by r0one — DISMISSED** [review]
Ok let's roll to english! Opened issue #242

**Pull request merged**
