### PR TITLE
Fix for issue #313 random 0 on navbar

### PR DESCRIPTION
**Pull request by noeamiot**

### CODE REVIEW

**Comment by NastuzziSamy** [comment]
Haha not random, I am just a bad developer 😂

**Review by NastuzziSamy — CHANGES_REQUESTED** [review]
Interesting approach but not the best. Here we want to display only if length > 0 

Better if you make a comparaison

**Comment by noeamiot** [comment]
I fixed it, I'll need some practice with react

**Review by MercierCorentin — APPROVED** [review]
OK now!

**Pull request merged**
